# Site settings
title: Nicholas Courtney
description: 
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site

# User settings
username: Nicholas Courtney
user_title: Electrical Engineer
email: 
github_username:  NicholasCourtney
linkedin_username: 

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
